export enum ActionTypes  {
  GET_FILMS= 'GET_FILMS',
  GET_FILMS_SUCCESS= 'GET_FILMS_SUCCESS',
  GET_FILMS_FAILURE= 'GET_FILMS_FAILURE',
  GET_PEOPLE = 'GET_PEOPLE',
  GET_PEOPLE_SUCCESS = 'GET_PEOPLE_SUCCESS',
  GET_PEOPLE_FAILURE = 'GET_PEOPLE_FAILURE',
  GET_STARSHIPS = 'GET_STARSHIPS',
  GET_STARSHIPS_SUCCESS = 'GET_STARSHIPS_SUCCESS',
  GET_STARSHIPS_FAILURE = 'GET_STARSHIPS_FAILURE',
  GET_PLANETS = 'GET_PLANETS',
  GET_PLANETS_SUCCESS = 'GET_PLANETS_SUCCESS',
  GET_PLANETS_FAILURE = 'GET_PLANETS_FAILURE',
  GET_VEHICLES = 'GET_VEHICLES',
  GET_VEHICLES_SUCCESS = 'GET_VEHICLES_SUCCESS',
  GET_VEHICLES_FAILURE = 'GET_VEHICLES_FAILURE'
}
