export const ActionTypes = {
  'AUTHENTICATE': 'AUTHENTICATE',
  'AUTHENTICATE_CHECK': 'AUTHENTICATE_CHECK',
  'AUTHENTICATE_SUCCESS': 'AUTHENTICATE_SUCCESS',
  'AUTHENTICATE_FAILURE': 'AUTHENTICATE_FAILURE',
  'LOGOUT': 'LOGOUT',
  'LOGOUT_SUCCESS': 'LOGOUT_SUCCESS',
  'LOGOUT_FAILURE': 'LOGOUT_FAILURE',
}
