export enum ActionTypes  {
  GET_FILMS= 'GET_FILMS',
  GET_FILMS_SUCCESS= 'GET_FILMS_SUCCESS',
  GET_FILMS_FAILURE= 'GET_FILMS_FAILURE',
  GET_PEOPLE = 'GET_PEOPLE',
  GET_PEOPLE_SUCCESS = 'GET_PEOPLE_SUCCESS',
  GET_PEOPLE_FAILURE = 'GET_PEOPLE_FAILURE'
}
